# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protofile_categories.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aprotofile_categories.proto\"!\n\x04Root\x12\x19\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x0b.categories\"+\n\ncategories\x12\x1d\n\ncategories\x18\x01 \x03(\x0b\x32\t.category\",\n\x08\x63\x61tegory\x12 \n\x08\x63\x61tegory\x18\x01 \x01(\x0b\x32\x0e.category_data\")\n\rcategory_data\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protofile_categories_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ROOT._serialized_start=30
  _ROOT._serialized_end=63
  _CATEGORIES._serialized_start=65
  _CATEGORIES._serialized_end=108
  _CATEGORY._serialized_start=110
  _CATEGORY._serialized_end=154
  _CATEGORY_DATA._serialized_start=156
  _CATEGORY_DATA._serialized_end=197
# @@protoc_insertion_point(module_scope)
